//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_Pracitce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FullName { get; set; }

        [Required(ErrorMessage = "Username is required")][StringLength(10, MinimumLength = 3)]
        public string Username { get; set; }

        [DataType(DataType.Password)] [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }
    }
}
