//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable2
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Salary { get; set; }
        public int DepartmentTable2Id { get; set; }
    
        public virtual DepartmentTable2 DepartmentTable2 { get; set; }


        public override string ToString()
        {
            return Id + " " + Name + " " + Salary + " " + DepartmentTable2Id;
        }
    }
}
